config/routes.rb
Streamable::Application.routes.draw do
  root :to => 'home#index'

  match 'users/logout' => 'application#logout'
  
  match 'streams/:id/broadcast' => 'streams#broadcast'
  match 'streams/index(/:params)' => 'streams#index'  
  resources :streams
  
  match 'users/logout' => 'application#logout'
  resources :users, :only => [:show, :new]
  
  resources :subscriptions, :only => [:create, :destroy]
  
  match 'auth/facebook/callback' => 'users#facebook_callback'
end

app/models/stream.rb
=begin
  Author : Gareth Aye (gareth@streamable.tv)
  Date : 04/21/12
=end
class Stream < ActiveRecord::Base
  attr_accessible :publisher_id,
                  :title,
                  :description,
                  :when,
                  :video_preview,
                  :opentok_session_id,
                  :publisher_token,
                  :price
                  
  belongs_to :publisher, :foreign_key => 'publisher_id', :class_name => 'User'
  has_many :subscriptions
  has_and_belongs_to_many :tags
  
  has_attached_file :video_preview,
                    :storage => :s3,
                    :s3_credentials => "#{Rails.root}/config/s3.yml"
  
  validates_presence_of :publisher,
                        :title,
                        :description,
                        :when,
                        :video_preview,
                        :opentok_session_id,
                        :publisher_token
  
  # TODO(gaye): If possible, replace this with a has_many :through
  def subscribers
    subscriptions.each(&:user)
  end
  
  def subscribed?(user)
    subscribers.include?(user)
  end
  
  # Expects an array of tags as input
  def self.find_by_tags(tags)
    streams = nil
    tags.each do |tag|
      # Make sure we're loading the streams of the tags eagerly
      streams_with_tag = Tag.find_by_name(tag, :include => :streams).streams
      streams ||= streams_with_tag
      streams = streams & streams_with_tag
      break if streams.empty?
    end
    
    streams
  end
end

app/controllers/streams_controller.rb
=begin
  Provides a RESTful collection of actions on streams
  OpenTok is used to manage live video sessions
  Author : Gareth Aye (gareth@streamable.tv)
  Date : 04/21/12
=end
class StreamsController < ApplicationController
  # GET /streams
  # GET /streams.json
  def index
    # TODO(gaye): We don't want an all query here 
    # we'd rather send some and then continue to load them in via ajax
    # This is a prohibitively expensive request otherwise
    @streams = 
        params[:tags] ? Stream.find_by_tags(params[:tags]) : Stream.all(:include => :publisher)   
    @tags = Tag.all
    
    respond_to do |format|
      format.html
      format.json { render :json => @streams }
    end
  end
  
  # GET /streams/1
  # GET /streams/1.json
  def show
    @stream = Stream.find(params[:id], :include => :publisher)
    @subscription = Subscription.new
    # TODO(gaye): Lookup whether current user is publisher/subscriber
    
    respond_to do |format|
      format.html
      format.json { render :json => @stream }
    end
  end
  
  # GET /streams/1/broadcast
  def broadcast
    @stream = Stream.find(params[:id], :include => :publisher)
    if @stream.publisher == current_user
      @publisher = true
      @token = @stream.publisher_token
    elsif @subscription = Subscription.find_by_stream_id_and_subscriber_id(@stream.id, current_user.id)
      @publisher = false
      @token = @subscription.subscriber_token
    else
      redirect_to @stream, :notice => 'No silly! You have to sign up first!'
    end
  end
  
  # GET /streams/new
  # GET /streams/new.json
  def new
    # TODO(gaye): Enforce permissions
    @stream = Stream.new
    @tags = Tag.all
    
    respond_to do |format|
      format.html
      format.json { render :json => @stream }
    end
  end
  
  # GET /streams/1/edit
  def edit
    @stream = Stream.find(params[:id], :include => :publisher)
    return unauthorized if @stream.publisher != current_user
  end
  
  # POST /streams
  # POST /streams.json
  def create
    # TODO(gaye): Enforce permissions
    session, token = 
        OpenTokHelper::create_session_and_generate_publisher_token(current_user, request.remote_addr)
    params[:stream][:publisher_id] = current_user.id
    params[:stream][:opentok_session_id] = session.session_id
    params[:stream][:publisher_token] = token
    
    @stream = Stream.new(params[:stream])
    @stream.tags = params[:tags].split(',').map {|t| Tag.find_or_create_by_name(t)}
    
    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, :notice => "Great! We'll see you at #{@stream.when}!" }
        format.json { render :json => @stream, :status => :created, :location => @stream }
      else
        format.html { render :action => 'new' }
        format.json { render :json => @stream.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /streams/1
  # PUT /streams/1.json
  def update
    @stream = Stream.find(params[:id], :include => :publisher)
    return unauthorized if @stream.publisher != current_user

    respond_to do |format|
      if @stream.update_attributes(params[:stream])
        format.html { redirect_to @stream, :notice => "Okay got it! We'll see you at #{@stream.when}!" }
        format.json { head :no_content }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @stream.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream = Stream.find(params[:id], :include => :publisher)
    return unauthorized if @stream.publisher != current_user
    
    @stream.destroy

    respond_to do |format|
      format.html { redirect_to streams_url }
      format.json { head :no_content }
    end
  end
  
  # capture notifications from the Zencoder service about video encoding
  def encode_notify
  end
end

app/helpers/streams_helper.rb
module StreamsHelper
  def truncate_to_words(string, n)
    shortened = truncate(string, :length => n, :omission => '')
    last_space = shortened.rindex(' ')
    "#{last_space ? shortened.slice(0..last_space - 1) : shortened}..."
  end
end

app/views/streams/_form.html.erb
<%= form_for(@stream) do |f| %>
  <% if @stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stream.errors.count, 'error') %> prohibited this stream from being saved:</h2>

      <ul>
      <% @stream.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1 id="instruction">
  </h1>
  
  <br />
  
  <div id="explanation">
  </div>
  
  <br /><br /><br /><br />

  <div class="field" id="title">
    <%= f.text_field :title %>
  </div>
  
  <div class="field" id="description">
    <%= f.text_area :description %>
  </div>
  
  <div class="field" id="video_preview">
    <%= f.file_field :video_preview %>
  </div>
  
  <div class="field" id="when">
    <%= f.datetime_select :when %>
  </div>
  
  <div class="field" id="price">
    <%= f.text_field :price %>
  </div>
  
  <div class="field" id="tags">
    <%= render :partial => 'tags', :locals => { :tags => @tags } %>
    <%= f.hidden_field :tags, :name => "tags" %>
  </div>
  
  <br /><br />
  
  <div id="continue">
    Continue
  </div>
  
  <div class="actions" id="submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/streams/_publisher.html.erb
<div id="publisher">
  <div id="publisher_video">
  </div>
</div>

<div id="subscribers">
</div>

<%= javascript_include_tag  'application' %>
<script src="http://staging.tokbox.com/v0.91/js/TB.min.js"></script>
<script type="text/javascript">
  var apiKey = "14128932";
  var sessionId = "<%= @stream.opentok_session_id %>";
  var token = "<%= @token %>";

  TB.setLogLevel(TB.DEBUG);

  var session = TB.initSession(sessionId);
  session.addEventListener('sessionConnected', sessionConnectedHandler);
  session.addEventListener('streamCreated', streamCreatedHandler);
  session.connect(apiKey, token);

  function sessionConnectedHandler(event) {
    session.publish('publisher_video', {'name' : 'publisher', 'width' : 600, 'height' : 400});
    subscribeToStreams(event.streams);
  }

  function streamCreatedHandler(event) {
    subscribeToStreams(event.streams);
  }
  
  function subscribeToStreams(streams) {
    for (var i = 0; i < streams.length; i++) {
      if (streams[i].connection.connectionId != session.connection.connectionId) {
        var div = document.createElement('div');
        div.setAttribute('id', 'subscriber' + streams[i].streamId);
        $('#subscribers').append(div);
        
        session.subscribe(streams[i], div.id);
      }
    }
  }
</script>

app/views/streams/_stream_preview.html.erb
<div class="preview_image">
  <div class="image">
    <%= image_tag 'placeholder.jpeg' %>
    <!-- TODO (armaansarkar): video thumbnail -->
  </div>
  
  <%= link_to truncate_to_words(stream.description, 240), stream, :class => 'preview_description' %>
</div>

<div class="preview_title">
  <%= link_to stream.title, stream %>
</div>

<div class="preview_publisher">
  <%= link_to format_name(stream.publisher), stream.publisher %>    
</div>

<div class="preview_time">
  <%= format_time(stream.when) %>    
</div>

app/views/streams/_subscriber.html.erb
<div id="publisher">
</div>

<div id="subscribers">
</div>

<%= javascript_include_tag  'application' %>
<script src="http://staging.tokbox.com/v0.91/js/TB.min.js"></script>
<script type="text/javascript">
  var apiKey = "14128932";
  var sessionId = "<%= @stream.opentok_session_id %>";
  var token = "<%= @token %>";

  TB.setLogLevel(TB.DEBUG);

  var session = TB.initSession(sessionId);
  session.addEventListener('sessionConnected', sessionConnectedHandler);
  session.addEventListener('streamCreated', streamCreatedHandler);
  session.connect(apiKey, token);
  
  function sessionConnectedHandler(event) {
    var div = document.createElement('div');
    div.setAttribute('id', 'me');
    $('#subscribers').append(div);
    session.publish('me');
    subscribeToStreams(event.streams);
  }

  function streamCreatedHandler(event) {
    subscribeToStreams(event.streams);
  }
  
  function subscribeToStreams(streams) {
    for (var i = 0; i < streams.length; i++) {
      if (streams[i].connection.connectionId != session.connection.connectionId) {
        var div;
        if (streams[i].name == 'publisher') {
          div = $('#publisher');
        } else {
          div = document.createElement('div');
          div.setAttribute('id', 'subscriber' + stream[i].streamId);
          $('#subscribers').append(div);
        }
        
        session.subscribe(streams[i], div.id);
      }
    }
  }
</script>

app/views/streams/_tags.html.erb
<div id="grade_slider">
  <% tags.delete_if {|t| t.name.to_i != 0} %>
  <br />
  
  <div id="ticks">
    <div class="tick">
    </div>
    <br />
    
    <% (6..12).each do |i| %>
      <div class="tick">
        <%= i %>
      </div>
    <% end %>
  </div>
  
  <div id="slider">
  </div>
</div>

<div id="tag_buttons">
  <% tags.each do |t| %>
    <div class="tag_button tag">
      <%= t.name %>
    </div>
  <% end %>
</div>

app/views/streams/broadcast.html.erb
<div id="broadcast">
  <%= render @publisher ? 'publisher' : 'subscriber' %>
</div>

app/views/streams/index.html.erb
<div id="index">
  <div id="dashboard">
    
  </div>
  <div id="content">
    <div id="message">
      <div id="main"> Find an awesome class to take. </div>
      <div id="sub"> Browse by grade level, subject area or both! </div>
    </div>
    <div id="categories">
      <%= render :partial => 'tags', :locals => { :tags => @tags } %>
    </div>

    <div id="streams">
      <% @streams.each_with_index do |s, i| %>
        <div class="preview">
          <%= render :partial => 'stream_preview', :locals => {:stream => s} %>
        </div>
        
        <% if i % 2 == 1 %>
          <div style="clear:both"></div>
        <% end %>
      <% end %>
    </div>
    <div style="clear:both"></div>
  </div>
  
  <div id="bottom">
    <div id="create_message">
      <div id="main">Have something valuable to teach?</div>
      <div id="sub">Create your very own stream!</div>
    </div>
    <br />
    <%= link_to "New Stream", new_stream_path, :id => "new_stream_button" %>
  </div>
</div>

app/views/streams/new.html.erb
<div id="form_container">
  <%= render 'form' %>
</div>

app/views/streams/show.html.erb
<!--
  Renders a stream
  Author : Gareth Aye (gareth@streamable.tv)
  Date : 04/21/12
-->

<%= javascript_include_tag 'http://connect.facebook.net/en_US/all.js#xfbml=1' %>

<div id="stream">
  <table id="streamtable">
    <tr>
      <td>
        <h2>
          <%= @stream.title %> 
        </h2>
      </td>
    </tr>

    <tr>
      <td>
        <div id="video_preview">
          <video src=<%= @stream.video_preview.url %> controls>
            Couldn't display video!
          </video>
        </div>
      </td>
    
      <td>
        <div id="description">
          <%= @stream.description %>
          
          <br /><br /><br /><br />

          <%= render 'subscriptions/form' %>
        </div>
      </td>
    </tr>
  
    <tr>
      <td>
        with <%= link_to(format_name(@stream.publisher), @stream.publisher) %>
        at <%= format_time(@stream.when) %>
      </td>
    </tr>
  </table>

  <div id="comments">
    <div id="fb-root"></div>
    <fb:comments href=<%= request.url %> width="700px"></fb:comments>
  </div>
</div>