config/routes.rb
Streamable::Application.routes.draw do
  root :to => 'home#index'

  match 'users/logout' => 'application#logout'
  
  match 'streams/:id/broadcast' => 'streams#broadcast'
  match 'streams/index(/:params)' => 'streams#index'  
  resources :streams
  
  match 'users/logout' => 'application#logout'
  resources :users, :only => [:show, :new]
  
  resources :subscriptions, :only => [:create, :destroy]
  
  match 'auth/facebook/callback' => 'users#facebook_callback'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streamable</title>
  <%= stylesheet_link_tag     'application', :media => 'all' %>
  <%= stylesheet_link_tag     'jquery-ui-1.8.19.custom.css' %>
  <%= javascript_include_tag  'application' %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <meta property="fb:app_id" content="206560469458633">
</head>
<body>
  <div id="header">
    <span id="logo">
      <%= link_to image_tag('streamable.png'), streams_path %>
    </span>
    
    <div id="user_panel">
      <% if user_logged_in? %>
        <span id="account">
          <%= link_to image_tag(current_user.image_url), user_path(current_user) %>
          <%= link_to format_name(current_user), user_path(current_user) %>
        </span>
        
        <span id="sign_out">
          <%= link_to 'Sign Out', users_logout_path %>
        </span>
      <% else %>
        <%= render 'users/login' %>
      <% end %>
    </div>
  </div>

  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streamable</title>
  <%= stylesheet_link_tag     'application', :media => 'all' %>
  <%= stylesheet_link_tag     'home' %>
  <%= javascript_include_tag  'home' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="landing">
    <div id="header">
      <div id="logo">
        <%= link_to image_tag('streamable.png'), streams_path %>
      </div>
    </div>
     
    <div id="home_container">
      <div id="instructions">
        <div id="big">
          Education's Live Video Marketplace.
        </div>

        Want to learn how to play the viola? 
        Need help balancing an equation?
        Ever wondered how to juggle? 
        <span class="pitch">We've got it all.</span>
        <br /><br />

        Have something to teach? 
        Can you do it over live video?
        <span class="pitch">Perfect.</span>
        <br /><br />
      </div>
    
      <%= render 'users/login' %>
      <%= link_to '...or check it out first!', streams_path, :id => 'checkit' %>   
      <div style="clear:both" />
    </div>
  
    <%= yield %>
  </div>
</body>
</html>